### ISSUE TITLE
MYSQL_ROOT_PASSWORD 

### ISSUE THREAD

**Issue by MartinN3** [jbergstroem/mariadb-alpine#13]
MYSQL_ROOT_PASSWORD is not used while importing db from docker-entrypoint-initdb.d.

**Comment by jbergstroem** [comment]
Hey, didn't see this until now. Will investigate, but at least the [init script seems to look for it](https://github.com/jbergstroem/mariadb-alpine/blob/master/run.sh#L25).

**Comment by jbergstroem** [comment]
@MartinN3 can you have another look? I tested everything end to end today and setting `MYSQL_ROOT_PASSWORD` worked for me.

**Comment by jbergstroem** [comment]
Closing this as $NEED_MORE_INFO. Feel free to reopen with how to reproduce.
