### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by jbergstroem** [jbergstroem/mariadb-alpine#17]
Since arm builders are relatively easy to arrange, we should investigate if we can generate these as part of CI as well. Also, we're not actually building stuff; so its more a matter of having the right test environments.

**Comment by jbergstroem** [comment]
Cross-compiling looks relatively trivial as well: https://github.com/ckulka/docker-multi-arch-example

**Comment by jbergstroem** [comment]
Relevant article about adding architecture metadata as part of the manifest: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by williamdes** [comment]
Example for tests: https://github.com/sudo-bot/nut-upsd/blob/main/.github/workflows/build.yml

Example for publish step: https://github.com/sudo-bot/nut-upsd/blob/main/.github/workflows/publish.yml

You will see in my example how to manually publish a manifest, that said it is not usefull and you can just ask docker buildx to build and push all the images and make the manifest

You may want to get into Docker image signing: https://github.com/sudo-bot/action-docker-sign

**Comment by jbergstroem** [comment]
@williamdes thanks for sharing! Will review over the weekend.

**Comment by williamdes** [comment]
> @williamdes thanks for sharing! Will review over the weekend.

Thank you so much !
I use `tobi312/rpi-mariadb` but think your image would be better, I do not know why MariaDB hits 100% CPU doing nothing.

You would save me if the image is built for my RaspberryPi

**Comment by jbergstroem** [comment]
> You would save me if the image is built for my RaspberryPi

I have a RPi as well (running Alpine aarch64) - can try and see if I can get it running.

**Comment by williamdes** [comment]
> > You would save me if the image is built for my RaspberryPi
> 
> I have a RPi as well (running Alpine aarch64) - can try and see if I can get it running.

Mine is a armv7l
Let me know if you need anything

**Comment by jbergstroem** [comment]
Better late than never :sad: I now have a test tag up - please help me in testing (ping @williamdes)! 

https://hub.docker.com/layers/jbergstroem/mariadb-alpine/test-multiarch/images/sha256-c13f4e65178580a745657faa26208af02ea478238846abc0c47c7e74fbf40358?context=repo

**Comment by jbergstroem** [comment]
I've just removed the test containers. A new release of `10.6.10` will happen shortly.

**Comment by williamdes** [comment]
> I've just removed the test containers. A new release of `10.6.10` will happen shortly.

Thank you !!
