### ISSUE TITLE
`mysqldump` is not included?

### ISSUE THREAD

**Issue by Luc45** [jbergstroem/mariadb-alpine#227]
Howdy, is `mysqldump` available in this image? Would it add too much size to add it?

**Comment by Luc45** [comment]
Opened a PR to see how many kbs it adds to the image: https://github.com/jbergstroem/mariadb-alpine/pull/229

**Comment by jbergstroem** [comment]
Thanks for opening the PR! As you also see; finding the middle ground between functionality and minimalism is hard.

Seeing how this is more of a client tool rather than server; I'm really on the fence.
