### ISSUE TITLE
Unable to clean start due to missing default mysql database caused by /usr/bin/ clean up

### ISSUE THREAD

**Issue by GTANAdam** [jbergstroem/mariadb-alpine#3]
### Unable to clean start due to missing default mysql database caused by /usr/bin/ clean up

It Appears that some missing binary from /usr/bin directory is giving it a hard time initialize the database.

#### here's what happens when you run mariadb-alpine:
>[ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
[Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
[ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
>[Note] Server socket created on IP: '::'.
[ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist

then crashes.

**Comment by GTANAdam** [comment]
Alright, found the culprit removed binary: resolveip

**Comment by GTANAdam** [comment]
I do not recall how but reintroducing it somehow fixes half of the issue

**Comment by jbergstroem** [comment]
>  EDIT: Ah, most likely because I used a hostname instead of an IP address in my docker

Ah; makes sense. I'll re-add it. The idea is obviously not to cripple the image, just find a balance between size and functionality.

..just wish there was a solution to #1 😢
