### ISSUE TITLE
New release strategy: introduce oldstable versions (`10.3.x`, `10.2.x`, ..)?

### ISSUE THREAD

**Issue by jbergstroem** [jbergstroem/mariadb-alpine#35]
I'm considering changing release strategy:
- [ ] `latest` points to latest release instead of latest build
- [ ] maintain multiple versions with the same setup, leading to multiple "stable" branches (and the burden of maintaining them) 

..not sure how big a demand would be for older versions of MariaDB. Since Alpine Linux doesn't really do LTS ([but does do some security backporting with small staffing](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases)) I'm not sure what the benefits would be. 

I'll keep this issue open for a bit to see if any of the users of this image has anything to add.

**Comment by williamdes** [comment]
Maybe just maintain the last 10.{i-0, i-1, i-2} ?

**Comment by jbergstroem** [comment]
> Maybe just maintain the last 10.{i-0, i-1, i-2} ?

Yeah; I was a bit more ambitious while writing this since I moved away from alpine due to the long-standing InnoDB issue bug and did a [completely custom-built image on top of rawhide](https://github.com/jbergstroem/mariadb-alpine/pull/53).

I will instead lean on alpine activity and write some job to track changes to the versions.

**Comment by jbergstroem** [comment]
> Maybe just maintain the last 10.{i-0, i-1, i-2} ?

Thinking we have to lean on how long alpine is maintaining their releases/backports for this!

**Comment by jbergstroem** [comment]
I will retire this until further notice due to discussions here and in linked PR's.
