### ISSUE TITLE
Move away from Alpine as container base 

### ISSUE THREAD

**Issue by jbergstroem** [jbergstroem/mariadb-alpine#49]
Seeing how Alpine and MariaDB are having longstanding issues that doesn't seem to find a resolution anytime soon, using another base while achieving a similarly minimal size would be a good next step.

I am currently building MariaDB from scratch in fedora:rawhide and will do a PR shortly that hopefully passes tests.

**Comment by jbergstroem** [comment]
A WIP container that passes tests locally is available here for testing. Any feedback much appreciated!
I will be running it on my zfs setup next to see if we are avoiding issues.

Check it out by pulling `jbergstroem/mariadb-alpine:test-rawhide-glibc` (yes, there will be a future naming issue 😄)

**Comment by sausix** [comment]
@jbergstroem 
... `Alpine and MariaDB are having longstanding issues` ...

Any link to details?
Thanks.

**Comment by jbergstroem** [comment]
@sausix lots of link in this issue: https://github.com/jbergstroem/mariadb-alpine/issues/1

**Comment by sausix** [comment]
Thanks.
It's mostly a (fixed) ZFS issue.

Databases on CoW (copy on write) systems should be handled with care generally.
You should mention it in the README.md.

I'm using btrfs on my host and prepared an empty directory for mariadb's data files with `chattr +C` to disable CoW for all new files and directories within it. Works for volumes too. It's important that the files are not created yet.

**Comment by jbergstroem** [comment]
> Databases on CoW (copy on write) systems should be handled with care generally.
> You should mention it in the README.md.

Want to open a PR? 😄 

> I'm using btrfs on my host and prepared an empty directory for mariadb's data files with chattr +C to disable CoW for all new files and directories within it. Works for volumes too. It's important that the files are not created yet.

Since we're talking in this issue; would you have issues with switching to a glibc-based host? Seeing how the bug is fixed upstream now (it lacked attention for a long time which is why I opened this) its less important from a bug perspective, but the amount of work I put into shaping the new container actually makes it both more optimized, more rigid to version updates (and what files to bundle) and likely more performant due to glibc.

**Comment by sausix** [comment]
> 
> Want to open a PR? 
> 
Maybe :-D
But currently totally busy with other Docker issues (poor IPv6 support) :-D

> would you have issues with switching to a glibc-based host?
No. I knew about Alpine but wasn't aware of it's benefits and small footprint.
musl is nice but not a requirement for me. If glibc is more performant, it's a good point.

I just hope you don't end on maintaining a full grown base image like ubuntu.

PR for README will come soon.

**Comment by jbergstroem** [comment]
> I just hope you don't end on maintaining a full grown base image like ubuntu.

The goals of this repository/project is to create the smallest-yet-fully-functional oci image possible.

**Comment by jbergstroem** [comment]
Going to close this since the bug is fixed in newer versions of MariaDB and we still want to lean on Alpine to achieve multi-arch support (arm, ..).
