### ISSUE TITLE
Add support for execution of SQL files and scripts in /docker-entrypoint-initdb.d 

### ISSUE THREAD

**Issue by mauricios** [jbergstroem/mariadb-alpine#5]
Other DB Docker images have the ability to execute SQL scripts and initialize DB the first time  using the directory `/docker-entrypoint-initdb.d`. This is useful for development since it is possible to easily have all the data when starting the container.

**Comment by jbergstroem** [comment]
Sounds reasonable. I'll look at getting it in shortly.

**Comment by jbergstroem** [comment]
@mauricios just added it in #6 - PTAL! Especially interested if my slightly different implementation would be a problem (if so, I can look at handling piping differently).
