### ISSUE TITLE
Add comparing against some other images

### ISSUE THREAD

**Issue by williamdes** [jbergstroem/mariadb-alpine#72]
- tobi312/rpi-mariadb
- [linuxserver/docker-mariadb](https://github.com/linuxserver/docker-mariadb) (looks like a serious project too)

**Comment by jbergstroem** [comment]
@williamdes out of curiosity, what type of comparisons would be beneficial to you? Right now I mostly focus on size.

**Comment by williamdes** [comment]
> @williamdes out of curiosity, what type of comparisons would be beneficial to you? Right now I mostly focus on size.

Size too ;)

I am using [Dive](https://github.com/wagoodman/dive) on your container and will try to make a PR in 30min to improve the layers

Your image is awesome 👏🏻 

I would also compare image layers, some people use Docker the wrong way and make useless layers

Example useless layers:

```Dockerfile
RUN rm /foo/bar
RUN rm /foo/baz
```
Use
```Dockerfile
RUN rm /foo/bar && \
         rm /foo/baz
```

And for stupid layers that add weight

```Dockerfile
RUN install package
RUN cleanup files
```

vs

```Dockerfile
RUN install package && \
         cleanup files
```

**Comment by jbergstroem** [comment]
> Example useless layers

Yeah, the project goes into great lengths to try and minimize the footprint since that was the main goal. I'm sure we've done local Wordpress development once or twice in our lives..
