### ISSUE TITLE
How to upgrade to MariaDB 10.5.9? 

### ISSUE THREAD

**Issue by kklepper** [jbergstroem/mariadb-alpine#85]
I have Dockerfiles for MariaDB 10.4.18 and 10.1.26 based on your model.

I tried to define a Dockerfile for version 10.5.9 along the same lines:

```
apk update add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main mariadb  mariadb-client && \ etc
but I don't get the server executable.
```

Looking at https://pkgs.alpinelinux.org/package/edge/main/x86/mariadb-common and then Contents of package I see there is no server, mainly language files.

The packages I am looking for seem to appear in above URL under Sub Packages. Nevertheless, they seem to be not implemented somehow. You can verify at docker hub kklepper/mariadb33-v10.5.9 

Do you have an idea what is happening here and how to make it work?

See also https://stackoverflow.com/questions/67912422/dockerfile-alpine-mariadb-latest

**Comment by kklepper** [comment]
I also used 

```
apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main mariadb=10.5.9-r0  mariadb-client && \
```
to no avail.

**Comment by kklepper** [comment]
I updated my [question](https://stackoverflow.com/questions/67912422/dockerfile-alpine-mariadb-latest/67926699#67926699) at stackoverflow.

**Comment by kklepper** [comment]
Well:

```
# docker images -f reference='alpine'
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
alpine       3.11      e389ae589224   8 weeks ago     5.62MB
alpine       3.12      13621d1b12d4   8 weeks ago     5.58MB
alpine       3.13      6dbb9cc54074   8 weeks ago     5.61MB
alpine       3.9       78a2ce922f86   13 months ago   5.55MB
alpine       3.3       a6fc1dbfa81a   2 years ago     4.82MB

```

Your recipe worked we,, so I changed my first line in Dockerfile-v10.5.9 from 

`apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main mariadb  mariadb-client mariadb-server-utils && \`

to 

`apk add --no-cache mariadb mariadb-client && \`

rebuilt, started and got no server. I'll have to leave now for an hour or so.

**Comment by kklepper** [comment]
Now I tested by removing `eval rm -rf "${path}"; \` -- `mysqld` is present, image is fat (186MB). 

Leaving this instruction size is 26MB, about half the size of version 10.4.18 which is itself remarkably small compared with my 10.1.26 version of 112MB.

```
# docker images | grep "mar"
kklepper/mariadb33-v10.5.9                               alpine          8e82df35b98a   34 seconds ago   26.2MB
kklepper/mariadb33-v10.1.26                              alpine          19905a582f5a   5 hours ago      112MB
kklepper/mariadb33-v10.4.18                              alpine          d575ee724fc2   21 hours ago     43.5MB
demyx/mariadb                                            latest          8452370517e1   4 days ago       190MB
mariadb                                                  latest          eff629089685   2 weeks ago      408MB
wodby/mariadb                                            latest          45eb42ec6a5e   4 weeks ago      272MB
yobasystems/alpine-mariadb                               latest          6229b748ebe8   5 weeks ago      231MB
kklepper/mariadb33                                       alpine          44b402734855   10 months ago    112MB
```

By the way, `kklepper/mariadb33` = `kklepper/mariadb33-v10.1.26` has been pulled from docker hub 7.2K times -- uh, without a description and no star? Even kklepper/mariadb33-v10.5.9 has been pulled 31 times -- must be my testing.

So obviously your fat trimming measure is successful -- but trims `mysqld` as well. So I echoed all candidates and did not find it:

```
usr/bin/mysqldump
usr/bin/mysqldumpslow
usr/bin/mysqlimport
usr/bin/mysqlshow
etc/my.cnf.d/mariadb-server.cnf
usr/share/mariadb/czech/errmsg.sys
usr/share/mariadb/danish/errmsg.sys
usr/share/mariadb/dutch/errmsg.sys
usr/share/mariadb/estonian/errmsg.sys
usr/share/mariadb/french/errmsg.sys
usr/share/mariadb/german/errmsg.sys
usr/share/mariadb/greek/errmsg.sys
usr/share/mariadb/hungarian/errmsg.sys
usr/share/mariadb/italian/errmsg.sys
usr/share/mariadb/japanese/errmsg.sys
usr/share/mariadb/korean/errmsg.sys
usr/share/mariadb/norwegian/errmsg.sys
usr/share/mariadb/norwegian-ny/errmsg.sys
usr/share/mariadb/polish/errmsg.sys
usr/share/mariadb/portuguese/errmsg.sys
usr/share/mariadb/romanian/errmsg.sys
usr/share/mariadb/russian/errmsg.sys
usr/share/mariadb/serbian/errmsg.sys
usr/share/mariadb/slovak/errmsg.sys
usr/share/mariadb/spanish/errmsg.sys
usr/share/mariadb/swedish/errmsg.sys
usr/share/mariadb/ukrainian/errmsg.sys
usr/bin/aria_dump_log
usr/bin/aria_ftdump
usr/bin/aria_pack
usr/bin/aria_read_log
usr/bin/aria_s3_copy
usr/bin/innochecksum
usr/bin/mariadb-binlog
usr/bin/mariadb-conv
usr/bin/mariadb-embedded
usr/bin/mariadb-install-db
usr/bin/mariadb-ldb
usr/bin/mariadb-plugin
usr/bin/mariadb-secure-installation
usr/bin/mariadb-slap
usr/bin/mariadb-tzinfo-to-sql
usr/bin/mariadbd
usr/bin/mariadbd-safe
usr/bin/msql2mysql
usr/bin/myisamchk
usr/bin/myisamlog
usr/bin/myisampack
usr/bin/myrocks_hotbackup
usr/bin/mysql_embedded
usr/bin/mysql_ldb
usr/bin/mysql_plugin
usr/bin/mysql_secure_installation
usr/bin/mysql_tzinfo_to_sql
usr/bin/mysqlbinlog
usr/bin/mysqld_safe
usr/bin/mysqlslap
usr/bin/replace
usr/bin/resolve_stack_dump
usr/bin/resolveip
usr/bin/sst_dump
usr/bin/test-connect-t
usr/bin/wsrep_sst_common
usr/bin/wsrep_sst_mariabackup
usr/bin/wsrep_sst_mysqldump
usr/bin/wsrep_sst_rsync
usr/bin/wsrep_sst_rsync_wan
usr/lib/mariadb/plugin/adt_null.so
usr/lib/mariadb/plugin/auth_0x0100.so
usr/lib/mariadb/plugin/auth_ed25519.so
usr/lib/mariadb/plugin/auth_pam.so
usr/lib/mariadb/plugin/auth_pam_v1.so
usr/lib/mariadb/plugin/auth_test_plugin.so
usr/lib/mariadb/plugin/daemon_example.ini
usr/lib/mariadb/plugin/debug_key_management.so
usr/lib/mariadb/plugin/dialog_examples.so
usr/lib/mariadb/plugin/disks.so
usr/lib/mariadb/plugin/example_key_management.so
usr/lib/mariadb/plugin/file_key_management.so
usr/lib/mariadb/plugin/func_test.so
usr/lib/mariadb/plugin/ha_connect.so
usr/lib/mariadb/plugin/ha_example.so
usr/lib/mariadb/plugin/ha_federated.so
usr/lib/mariadb/plugin/ha_s3.so
usr/lib/mariadb/plugin/ha_spider.so
usr/lib/mariadb/plugin/ha_test_sql_discovery.so
usr/lib/mariadb/plugin/handlersocket.so
usr/lib/mariadb/plugin/libdaemon_example.so
usr/lib/mariadb/plugin/locales.so
usr/lib/mariadb/plugin/metadata_lock_info.so
usr/lib/mariadb/plugin/mypluglib.so
usr/lib/mariadb/plugin/qa_auth_client.so
usr/lib/mariadb/plugin/qa_auth_interface.so
usr/lib/mariadb/plugin/qa_auth_server.so
usr/lib/mariadb/plugin/query_cache_info.so
usr/lib/mariadb/plugin/query_response_time.so
usr/lib/mariadb/plugin/server_audit.so
usr/lib/mariadb/plugin/simple_password_check.so
usr/lib/mariadb/plugin/sql_errlog.so
usr/lib/mariadb/plugin/test_sql_service.so
usr/lib/mariadb/plugin/test_versioning.so
usr/lib/mariadb/plugin/type_mysql_json.so
usr/lib/mariadb/plugin/type_test.so
usr/lib/mariadb/plugin/wsrep_info.so
usr/lib/mariadb/plugin/auth_pam_tool_dir/auth_pam_tool
usr/share/pam_user_map.so
usr/share/user_map.conf
usr/share/mariadb/binary-configure
usr/share/mariadb/errmsg-utf8.txt
usr/share/mariadb/magic
usr/share/mariadb/maria_add_gis_sp.sql
usr/share/mariadb/mysql-log-rotate
usr/share/mariadb/mysql.server
usr/share/mariadb/mysql_test_data_timezone.sql
usr/share/mariadb/mysql_test_db.sql
usr/share/mariadb/mysql_to_mariadb.sql
usr/share/mariadb/mysqld_multi.server
usr/share/mariadb/wsrep.cnf
usr/share/mariadb/wsrep_notify
usr/share/mariadb/hindi/errmsg.sys
usr/share/mariadb/policy/apparmor/README
usr/share/mariadb/policy/apparmor/usr.sbin.mysqld
usr/share/mariadb/policy/apparmor/usr.sbin.mysqld.local
usr/share/mariadb/policy/selinux/README
usr/share/mariadb/policy/selinux/mariadb-server.fc
usr/share/mariadb/policy/selinux/mariadb-server.te
usr/share/mariadb/policy/selinux/mariadb.te
```
So how come `mysqld`  vanished? What do I overlook here?

**Comment by jbergstroem** [comment]
> So how come `mysqld` vanished? What do I overlook here?

Because its called `mariadb` in 10.5.x. You can probably just copy my work [in the 10.5.x PR](https://github.com/jbergstroem/mariadb-alpine/pull/68) if you want something you can use – as mentioned previously, I will revamp tests before merging it.

**Comment by kklepper** [comment]
Thank you very much for spending so much time and effort instructing me. 

> Because most mysql related files are renamed to mariadb in 10.5.x.

Why? You mention it in 

```
  TO_KEEP=$(echo " \
    usr/bin/mysql$ \
    usr/bin/mysqld$ \
    usr/bin/mariadb$ \

```
and `mariadbd` ist not among those to be deleted.

> You can probably just copy my work in the 10.5.x PR if you want something you can use

```
Step 5/14 : COPY sh/clean.sh /clean.sh
COPY failed: file not found in build context or excluded by .dockerignore: stat sh/clean.sh: file does not exist
```

Ok, works so far (156MB).


```
/ # which mysqld
/usr/bin/mysqld
``` 
Next problem: `mysqld` will not write ` /var/run/mysqld/mysqld.sock`

I had this before and don't remember how to overcome this:
```
/ # mysqld &
/ # 2021-06-11  0:00:25 0 [Note] mysqld (mysqld 10.5.9-MariaDB-log) starting as process 202 ...

[1]+  Done(1)                    mysqld
/ # ls -latr /var/run/mysqld/mysqld.sock
ls: /var/run/mysqld/mysqld.sock: No such file or directory
```

In my understanding the socket and pid files should be written by the server immediately after start and deleted at shutdown to the path defined in `my.cnf` no matter what.

I get `mysqld` with inhibiting the removal instruction as well. And then my startup routine works as expected. So what is happening here?

So far so good, except the fat image, but there is another problem I had with 10.4.18 as well and already reported to [MariaDB](https://jira.mariadb.org/browse/MDEV-25892):

```
M:2521920 [(none)]>INSTALL SONAME 'ha_sphinx';
ERROR 1126 (HY000): Can't open shared library '/usr/lib/mariadb/plugin/ha_sphinx.so' (errno: 13, Error relocating /usr/lib/mariadb/plugin/ha_sphinx.so: _ZNK30Type_handler_hybrid_field_type26get_handler_by_result_typeE11Item_r)

```
Of course, the file ist there:

```
/ # ls -latr /usr/lib/mariadb/plugin/ha_sphinx.so
-rwxr-xr-x    1 root     root         96320 Oct  3  2019 /usr/lib/mariadb/plugin/ha_sphinx.so
```
I understand relocation is the problem, but to where, and why doesn't it work?

**Comment by jbergstroem** [comment]
> and mariadbd ist not among those to be deleted.

I haven't tested `10.5.9` but the PR gives me a working image with a similar size that my `10.4.x` series. Perhaps you can check out the branch and attempt building it?

> `/ # which mysqld`
> `/usr/bin/mysqld`

I believe this may be a symlink. I kept it due to referencing it in startup filies.

> ls: /var/run/mysqld/mysqld.sock: No such file or directory

If you invoke mysqld directly, it uses default socket path. Neither Alpine nor my interpretation of this uses a "naked" invocation.

> So far so good, except the fat image, but there is another problem I had with 10.4.18 as well and already reported to MariaDB:

As part of compromising between size and out-of-the-box functionality, I opted to not messing around with third party plugins too much. I can't really support this, but I can consider having a look at some point.

I will provide a working `10.5.x` release in the coming weeks, but other than that I think I will focus on finishing my test suite so I can ensure that functionality works across the release series, as well as guaranteeing stability.

**Comment by kklepper** [comment]
You are right:
```
`/ # ls -latr /usr/bin/mysqld
lrwxrwxrwx    1 root     root             8 Jun 11 00:11 /usr/bin/mysqld -> mariadbd
```

> but the PR gives me a working image

Hm, I'll have a look tomorrow, right now this is chinese to me.

> If you invoke mysqld directly, it uses default socket path.

Ok, I understand.

> As part of compromising between size and out-of-the-box functionality, I opted to not messing around with third party plugins too much. I can't really support this, but I can consider having a look at some point.

I see from the comments in my 10.1.26 Dockerfile that to begin with I had to manually `#COPY ha_sphinx.so /usr/lib/mysql/plugin` -- so at some point this was not necessary anymore for some reason. As told in [cannot INSTALL SONAME 'ha_sphinx';](https://jira.mariadb.org/browse/MDEV-25892) I have 36 plugins in 10.1.26 without me doing anything to this end. Therefore I suspected that the alpine package provided for them.

I think that the guys at MariaDB should explain the enigmatic error message.

**Comment by jbergstroem** [comment]
> Hm, I'll have a look tomorrow, right now this is chinese to me.

If you want to learn / investigate - dig in! If you are happy as a user, just give me a bit of time.

> I think that the guys at MariaDB should explain the enigmatic error message.

This is probably not a bug, just a consequence of shaving off bytes.

**Comment by jbergstroem** [comment]
> What now? I thought the branch would give me a direct git-link, but it is the same. What am I to do now?

You [need to check out the branch](https://git-scm.com/docs/git-checkout): `git checkout version/mariadb-10.5.8`

Sorry if this comes off as a bit blunt, but I believe we are venturing outside of what I can provide support for. I will provide a working `10.5.x` release relatively soon as well as quickly investigate whether or not sphinx is meant to work in the base distribution.

**Comment by kklepper** [comment]
Thank you. I'll try my best.

> Sorry if this comes off as a bit blunt, but I believe we are venturing outside of what I can provide support for. I will provide a working 10.5.x release relatively soon as well as quickly investigate whether or not sphinx is meant to work in the base distribution.

I'm very much OK with that. Let's see what MariaDB has to say. They don't seem to deliver sphinx.so anymore.

**Comment by kklepper** [comment]
I'm sorry, I have to correct myself. Looking again, everything is as expected, plugins are in `/usr/lib64/mysql/plugin`. 

```
# mysqld --print-defaults
mysqld would have been started with the following arguments:
```

As we have no arguments, the following is built in in 10.5.10:

```
MariaDB [(none)]> SHOW VARIABLES LIKE '%plu%';
+-----------------+--------------------------+
| Variable_name   | Value                    |
+-----------------+--------------------------+
| plugin_dir      | /usr/lib64/mysql/plugin/ |
| plugin_maturity | gamma                    |
+-----------------+--------------------------+
2 rows in set (0.007 sec)
```

I don't think I hallucinated back 3 hours ago and don't have an explanation for this. 

Well, look twice: it is `lib64`, not `lib` and `mysql`, not `mariadb`, which is somehow not quite consistent:

```
# ls -latr /usr/lib/mariadb/plugin
ls: cannot access '/usr/lib/mariadb/plugin': No such file or directory

# ls -latr /usr/lib64/mariadb/plugin
ls: cannot access '/usr/lib64/mariadb/plugin': No such file or directory

# ls -latr /usr/lib/mysql/plugin
ls: cannot access '/usr/lib/mysql/plugin': No such file or directory

# ls -latr /usr/lib64/mysql/plugin/ha_sphinx.so
-rwxr-xr-x 1 root  root  149304 May  6 10:29 ha_sphinx.so

# ls -latr /usr/lib/mariadb/ha_sphinx.so
-rwxr-xr-x 1 root root 96320 Jun 11 18:13 /usr/lib/mariadb/ha_sphinx.so
```
So this was an insight from 10.5.10 on host:

There is no /usr/lib/mariadb/plugin, but  /usr/lib64/mysql/plugin/ has all the files, and additionally /usr/lib/mariadb/ has the installed plugin.

Maybe it is just a hickup in renaming things. Let's try and define the plugin_dir.

In the Dockerfiles, I made sure I created the directory `/usr/lib64/mariadb/plugin` and copied `ha_sphinx.so` to this folder, then changed `my.cnf` and added `plugin_dir=/usr/lib64/mysql/plugin/`. 

This did not help for `10.4.18`, though:

```
M:2521920 [(none)]>select version();
+---------------------+
| version()           |
+---------------------+
| 10.4.18-MariaDB-log |
+---------------------+
1 row in set (0.000 sec)

M:2521920 [(none)]>SHOW VARIABLES LIKE 'plu%';
+-----------------+--------------------------+
| Variable_name   | Value                    |
+-----------------+--------------------------+
| plugin_dir      | /usr/lib64/mysql/plugin/ |
| plugin_maturity | gamma                    |
+-----------------+--------------------------+
2 rows in set (0.001 sec)

M:2521920 [(none)]>INSTALL SONAME 'ha_sphinx';
ERROR 1126 (HY000): Can't open shared library '/usr/lib64/mysql/plugin/ha_sphinx.so' (errno: 13, Error relocating /usr/lib64/mysql/plugin/ha_sphinx.so: _ZNK30Type_handler_hybrid_field_type26get_handler_by_result_typeE11Item_r)
```
This is the same error I get with `10.5.9`. If I omit the plugin_dir  directive, plugin_dir = /usr/lib/mariadb/plugin/, but it makes no difference.

So for me this is proof it is not a docker or container definition problem. 

I will test with 10.4 if I can. Well, I cannot. I removed 10.5, installed 10.4, started, but got an error.

```
# systemctl status mariadb
● mariadb.service - MariaDB 10.4.19 database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Sat 2021-06-12 01:59:44 CEST; 5min ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 1736166 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 1736156 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`cd /usr/bin/..; /usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR |>
  Process: 1736154 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
 Main PID: 1736166 (code=exited, status=1/FAILURE)
   Status: "MariaDB server is down"
```
I give up for now.

**Comment by kklepper** [comment]
Well, `stackoverflow` came to the rescue: first `rm -rf /var/lib/mysql`, too.

```
# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.4.19-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select version();
+-----------------+
| version()       |
+-----------------+
| 10.4.19-MariaDB |
+-----------------+
1 row in set (0.000 sec)

MariaDB [(none)]> SHOW VARIABLES LIKE '%plu%';
+-----------------+--------------------------+
| Variable_name   | Value                    |
+-----------------+--------------------------+
| plugin_dir      | /usr/lib64/mysql/plugin/ |
| plugin_maturity | gamma                    |
+-----------------+--------------------------+
2 rows in set (0.002 sec)

MariaDB [(none)]> INSTALL SONAME 'ha_sphinx';
Query OK, 0 rows affected (0.002 sec)
```

To me, this looks like the problem does relate to docker or alpine.

**Comment by jbergstroem** [comment]
> To me, this looks like the problem does relate to docker or alpine.

As I mentioned previously, I think this is by design (not a bug, but intentional). I believe [you have the answer here]( https://git.alpinelinux.org/aports/tree/main/mariadb/APKBUILD#n162).

**Comment by kklepper** [comment]
Thank you very much. I passed this on to Daniel Black from MariaDB with my questions:

>So the Alpine-maintainer of MariaDB is in charge? Do I understand correctly the Alpine compiles MariaDB without Sphinx? The error message is by MariaDB, not Alpine, right? And it would be triggered by the omission in the build process?

**Comment by jbergstroem** [comment]
> Thank you very much. I passed this on to Daniel Black from MariaDB with my questions

No worries. It is important to consider that Alpine is a Linux distribution that intentionally trades functionality for size.

**Comment by kklepper** [comment]
Daniel Black closed the case with


>        Resolution: Not a Bug
> 
> > So the Alpine-maintainer of MariaDB is in charge?
> 
> Yes.
> 
> >  Do I understand correctly the Alpine compiles MariaDB without Sphinx?
> 
> Yes.
> 
> > The error message is by MariaDB, not Alpine, right?
> 
> ":errno: 13, Error relocating" is caused by copying around a file that is tightly coupled build process and mariadb version and the dynamic loader not handling it.
> 
> > And it would be triggered by the omission in the build process?
> 
> Its triggered by YOU, who ignored "Google copy/paste/no analysis/move file X will just end in tears like where you started".
> 
> Stop using alpine based containers for sphinxse. It obviously doesn't work. The reasons the official docker image isn't alpine is it isn't actually tested prior to release (https://github.com/MariaDB/mariadb-docker/pull/343), though the alpine maintainers run some tests.
> 
> The reasons the official Docker Library mariadb does actually work is because it has sphinx as part of the image already.
> 

and 

>Final notes:
> 
> * Use a officially supported image - https://hub.docker.com/_/mariadb - packaging bugs of anything don't belong here (though we'll try to address crashes and other bugs).
> * Stop copying around files especially shared library and expect them to magicly work (host OS != container OS).
> * Use {{docker logs containername}} in bug reports (not used once in this bug report by you)
> * You can't just up/downgrade mariadb 10.1 -> 10.5 and back to 10.4 hence you jumping on a remove the datadir.
> * Slow down and analyze and learn (and much less copy whatever google result returned).

**Comment by kklepper** [comment]
Thank you very much for your patience.

**Comment by jbergstroem** [comment]
> Thank you very much for your patience.

No worries. I think his last comment was insightful and something I would also suggest. Try to do things a bit slower, every time you face a wall; it doesn't necessarily have to be built by someone else. Also, have fun!
